[package]
name = "dyn-web"
version = "0.1.0"
edition = "2021"

[build-dependencies]
regex = "1"
serde = "1"
serde_yaml = "0.9"

[dependencies]
serde = "1"
actix-web = "4"
mongodb = {version = "2.1.0", default-features = false, features = ["sync"]}