[package]
name = "dyn-web"
version = "0.1.0"
edition = "2021"

[lib]
name = "model"
path = "src/model.rs"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
actix-web = "4"